# Test goal: old versions of GCC with CUDA; GPU communications with OpenMPI
# Test intents (should change rarely and conservatively):
#   OS: Ubuntu oldest supported
#   Compiler: GCC oldest supported
#   GPU: CUDA oldest supported
#   HW: NVIDIA GPU, single NVIDIA GPU
#   MPI: OpenMPI
#   Features: GPU direct communications + update (unit tests), HeFFTe for GPU PME decomposition
#   Scope: configure, build, unit tests
# Test implementation choices (free to change as needed):
#   OS: Ubuntu 20.04
#   Build type: Debug
#   Compiler: GCC 9
#   GPU: CUDA 11.0.3
#   SIMD: SSE 4.1
#   FFT: FFTW3
#   Parallelism nt/ntomp: 4/2 (unit tests)

gromacs:gcc-9-cuda-11.0.3:configureMPI:
  extends:
    - .gromacs:base:configure
    - .use-gcc:base
    - .use-cuda
    - .use-mpi
  rules:
    - !reference [.rules:merge-and-post-merge-acceptance, rules]
  image: ${CI_REGISTRY}/gromacs/gromacs/ci-ubuntu-20.04-gcc-9-cuda-11.0.3
  variables:
    CMAKE: /usr/local/cmake-3.21.2/bin/cmake
    CMAKE_SIMD_OPTIONS: "-DGMX_SIMD=SSE4.1"
    CMAKE_EXTRA_OPTIONS: "-DGMX_USE_HEFFTE=ON"
    COMPILER_MAJOR_VERSION: 9

gromacs:gcc-9-cuda-11.0.3:buildMPI:
  extends:
    - .gromacs:base:build
    - .before_script:default
    - .use-ccache
  rules:
    - !reference [.rules:merge-and-post-merge-acceptance, rules]
  image: ${CI_REGISTRY}/gromacs/gromacs/ci-ubuntu-20.04-gcc-9-cuda-11.0.3
  variables:
    CMAKE: /usr/local/cmake-3.21.2/bin/cmake
  needs:
    - job: gromacs:gcc-9-cuda-11.0.3:configureMPI

gromacs:gcc-9-cuda-11.0.3:testMPI:
  extends:
    - .gromacs:base:test
  rules:
    - !reference [.rules:skip-if-single-nvidia-gpu-unavailable, rules]
    - !reference [.rules:merge-requests, rules]
  image: ${CI_REGISTRY}/gromacs/gromacs/ci-ubuntu-20.04-gcc-9-cuda-11.0.3
  variables:
    CMAKE: /usr/local/cmake-3.21.2/bin/cmake
    GMX_ENABLE_DIRECT_GPU_COMM: 1
    GMX_GPU_PME_DECOMPOSITION: 1
    GMX_TEST_LABELS: "QuickGpuTest|SlowGpuTest"
    GPU_VENDOR: "NVIDIA"
    GPU_COUNT: 1
  tags:
    - $GITLAB_RUNNER_TAG_1X_NVIDIA_GPU
  needs:
    - job: gromacs:gcc-9-cuda-11.0.3:buildMPI
