# Test goal: CUDA GPU communications with OpenMPI
# Test intents (should change rarely and conservatively):
#   OS: Ubuntu newest supported
#   GPU: CUDA newest supported with nvc++
#   HW: NVIDIA GPU
#   MPI: OpenMPI
#   Features: GPU direct communications (manual) + PME decomposition
#   Scope: configure, build, tests, regression tests
# Test implementation choices (free to change as needed):
#   OS: Ubuntu 22.04
#   Build type: RelWithDebInfo
#   Compiler: NVC++ 24.1
#   GPU: CUDA 12.3
#   SIMD: SSE 4.1
#   FFT: FFTW3
#   Parallelism np/ntomp: 4/1 (regression tests with a GPU)

gromacs:nvcxx-24.1-cuda-12.3.0:configureMPI:
  extends:
    - .gromacs:base:configure
    - .use-cuda
    - .use-mpi
  rules:
    - !reference [.rules:post-merge-acceptance, rules]
  image: ${CI_REGISTRY}/gromacs/gromacs/ci-ubuntu-22.04-gcc-11-cuda-12.3.0
  variables:
    CMAKE: /usr/local/cmake-3.21.2/bin/cmake
    CMAKE_SIMD_OPTIONS: "-DGMX_SIMD=SSE4.1"
    CMAKE_EXTRA_OPTIONS: "-DCMAKE_CXX_FLAGS='--diag_suppress=2828,111,1408,490,550,177,unrecognized_attribute,integer_sign_change,implicit_return_from_non_void_function,partial_override,code_is_unreachable'
                          -DGMX_USE_CUFFTMP=ON -DcuFFTMp_ROOT=/opt/nvidia/hpc_sdk/Linux_x86_64/24.1/math_libs/12.3
                          -DCMAKE_CXX_COMPILER=/opt/nvidia/hpc_sdk/Linux_x86_64/24.1/compilers/bin/nvc++
                          -DCMAKE_C_COMPILER=/opt/nvidia/hpc_sdk/Linux_x86_64/24.1/compilers/bin/nvc"

gromacs:nvcxx-24.1-cuda-12.3.0:buildMPI:
  extends:
    - .gromacs:base:build
    - .before_script:default
    # - .use-ccache # Disable CCache since it does not work correctly with NVC++ 24.1
  rules:
    - !reference [.rules:post-merge-acceptance, rules]
  image: ${CI_REGISTRY}/gromacs/gromacs/ci-ubuntu-22.04-gcc-11-cuda-12.3.0
  variables:
    CMAKE: /usr/local/cmake-3.21.2/bin/cmake
  needs:
    - job: gromacs:nvcxx-24.1-cuda-12.3.0:configureMPI

gromacs:nvcxx-24.1-cuda-12.3.0:testMPI:
  extends:
    - .gromacs:base:test
  rules:
    - !reference [.rules:skip-if-single-nvidia-gpu-unavailable, rules]
    - !reference [.rules:post-merge-acceptance, rules]
  image: ${CI_REGISTRY}/gromacs/gromacs/ci-ubuntu-22.04-gcc-11-cuda-12.3.0
  variables:
    CMAKE: /usr/local/cmake-3.21.2/bin/cmake
    GMX_ENABLE_DIRECT_GPU_COMM: 1
    GMX_GPU_PME_DECOMPOSITION: 1
    # Flag that cuFFTMp should be disabled when running on incompatible devices
    GMX_CI_DISABLE_CUFFTMP_DECOMPOSITION_ON_INCOMPATIBLE_DEVICES: 1
    # Location of CUDA FFT library, required for preload to avoid cuFFTMp on incompatible devices 
    CUFFTLIB: "/opt/nvidia/hpc_sdk/Linux_x86_64/24.1/math_libs/lib64/libcufft.so"
    # cuFFTMp uses NVSHMEM, which in turn will use NCCL on single-node when available
    # But NCCL has extra restrictions (such as only 1 rank per GPU) so we disable for CI
    NVSHMEM_DISABLE_NCCL: 1
    # Default NVSHMEM_SYMMETRIC_SIZE is around 1.5GB which causes mem allocation error on CI
    # GPUs having 4GB vidmem also this size is overkill for PME decomp tests, hence we
    # restrict the default NVSHMEM heap size to 32MB.
    NVSHMEM_SYMMETRIC_SIZE: 32M
    # set CUDA Module load to be lazy in order to save on CUDA libraries memory footprint
    # as without lazy loading whole cuFFTMp library may get loaded into GPU RAM.
    CUDA_MODULE_LOADING: LAZY
    # set nvshmem cumem allocation granularity to 2MB, default is 512MB.
    NVSHMEM_CUMEM_GRANULARITY: 2097152
    GMX_TEST_LABELS: "QuickGpuTest|SlowGpuTest"
    GPU_VENDOR: "NVIDIA"
    GPU_COUNT: 1
  tags:
    - $GITLAB_RUNNER_TAG_1X_NVIDIA_GPU
  needs:
    - job: gromacs:nvcxx-24.1-cuda-12.3.0:buildMPI

gromacs:nvcxx-24.1-cuda-12.3.0:regressiontest-gpucommupd-MPI:
  # Test parallelism np/ntomp: 4/1
  # Test parallelism GPU: direct communications, update
  extends:
    - .gromacs:base:regressiontest
  rules:
    - !reference [.rules:skip-if-single-nvidia-gpu-unavailable, rules]
    - !reference [.rules:post-merge-acceptance, rules]
  image: ${CI_REGISTRY}/gromacs/gromacs/ci-ubuntu-22.04-gcc-11-cuda-12.3.0
  variables:
    CMAKE: /usr/local/cmake-3.21.2/bin/cmake
    REGRESSIONTEST_PME_RANK_NUMBER: 0
    REGRESSIONTEST_TOTAL_RANK_NUMBER: 4
    REGRESSIONTEST_OMP_RANK_NUMBER: 1
    REGRESSIONTEST_PARALLEL: "-np"
    GMX_ENABLE_DIRECT_GPU_COMM: 1
    GPU_VENDOR: "NVIDIA"
    GPU_COUNT: 1
  tags:
    - $GITLAB_RUNNER_TAG_1X_NVIDIA_GPU
  needs:
    - job: gromacs:nvcxx-24.1-cuda-12.3.0:buildMPI
    - job: regressiontests:prepare
  artifacts:
    paths:
      - regressiontests
    when: always
    expire_in: 1 week

