# Test goal: code coverage with newest GCC
# Test intents (should change rarely and conservatively):
#   OS: Ubuntu newest supported
#   Compiler: GCC
#   GPU: no
#   Scope: configure, build, unit tests, coverage
# Test implementation choices (free to change as needed):
#   OS: Ubuntu 22.04
#   Build type: Debug
#   Compiler: GCC 12
#   MPI: thread_MPI
#   SIMD: AVX2_256
#   Parallelism nt/ntomp: 4/2 (unit tests)

gromacs:gcc-12:coverage:configure:
  extends:
    - .gromacs:base:configure
    - .use-gcc:base
  rules:
    - !reference [.rules:post-merge-acceptance, rules]
  image: ${CI_REGISTRY}/gromacs/gromacs/ci-ubuntu-22.04-gcc-12-rocm-5.4.1
  variables:
    CMAKE: /usr/local/cmake-3.18.4/bin/cmake
    CMAKE_SIMD_OPTIONS: "-DGMX_SIMD=AVX2_256"
    CMAKE_EXTRA_OPTIONS: "-DGMX_BUILD_FOR_COVERAGE=ON"
    COMPILER_MAJOR_VERSION: 12

gromacs:gcc-12:coverage:build:
  extends:
    - .gromacs:base:build
    - .before_script:default
    - .use-ccache
  rules:
    - !reference [.rules:post-merge-acceptance, rules]
  image: ${CI_REGISTRY}/gromacs/gromacs/ci-ubuntu-22.04-gcc-12-rocm-5.4.1
  variables:
    CMAKE: /usr/local/cmake-3.18.4/bin/cmake
  needs:
    - job: gromacs:gcc-12:coverage:configure

gromacs:coverage:analyse:
  variables:
    CMAKE: /usr/local/cmake-3.18.4/bin/cmake
    VENVPATH: "/root/venv/py3.7"
  rules:
    - !reference [.rules:post-merge-acceptance, rules]
  stage: post-test
  image: ${CI_REGISTRY}/gromacs/gromacs/ci-ubuntu-22.04-gcc-12-rocm-5.4.1
  needs:
    - job: gromacs:gcc-12:coverage:build

  script:
    - source $VENVPATH/bin/activate
    - mkdir public
    - outputdir=`pwd`/public
    - cd $BUILD_DIR
    - ctest -T test ctest -T coverage || true
  coverage: '/Percentage.*\: (\d+\.\d+)\%/'
  artifacts:
    paths:
      - $BUILD_DIR/Testing/`head -n 1 < $BUILD_DIR/Testing/TAG`/
    reports:
      coverage_report:
        coverage_format: cobertura
        path: $BUILD_DIR/Testing/`head -n 1 < $BUILD_DIR/Testing/TAG`/Coverage.xml
