# Test goal: Clang-CUDA build
# Test intents (should change rarely and conservatively):
#   OS: Ubuntu newest supported
#   GPU: Clang CUDA
#   HW: NVIDIA GPU
#   Scope: configure, build, unit tests, regression tests
# Test implementation choices (free to change as needed):
#   OS: Ubuntu 24.04
#   Build type: RelWithDebInfo
#   Compiler: Clang 20
#   MPI: thread_MPI
#   GPU: Clang CUDA 12.8.1
#   SIMD: AVX2_256, no kernels
#   FFT: FFTW3
#   Parallelism nt/ntomp: 4/2 (unit tests)
#   Parallelism nt/ntomp: 2/1 (regression tests)

gromacs:clang-20-cuda-12.8.1:configure:
  extends:
    - .gromacs:base:configure
    - .use-clang:base
    - .use-cuda
  rules:
    - !reference [.rules:post-merge-acceptance, rules]
  image: ${CI_REGISTRY}/gromacs/gromacs/ci-ubuntu-24.04-llvm-20-cuda-12.8.1-adaptivecpp-25.10.0-rocm-7.0.2
  variables:
    CMAKE: /usr/local/cmake-4.0.5/bin/cmake
    CMAKE_SIMD_OPTIONS: "-DGMX_USE_SIMD_KERNELS=off"
    CMAKE_EXTRA_OPTIONS: "-DGMX_CLANG_CUDA=ON"
    CMAKE_BUILD_TYPE_OPTIONS: "-DCMAKE_BUILD_TYPE=RelWithDebInfo"
    COMPILER_MAJOR_VERSION: 20

gromacs:clang-20-cuda-12.8.1:build:
  extends:
    - .gromacs:base:build
    - .use-clang:base
    - .use-ccache
  rules:
    - !reference [.rules:post-merge-acceptance, rules]
  image: ${CI_REGISTRY}/gromacs/gromacs/ci-ubuntu-24.04-llvm-20-cuda-12.8.1-adaptivecpp-25.10.0-rocm-7.0.2
  variables:
    CMAKE: /usr/local/cmake-4.0.5/bin/cmake
  needs:
    - job: gromacs:clang-20-cuda-12.8.1:configure

gromacs:clang-20-cuda-12.8.1:test:
  extends:
    - .gromacs:base:test
  rules:
    - !reference [.rules:skip-if-single-nvidia-gpu-unavailable, rules]
    - !reference [.rules:post-merge-acceptance, rules]
  image: ${CI_REGISTRY}/gromacs/gromacs/ci-ubuntu-24.04-llvm-20-cuda-12.8.1-adaptivecpp-25.10.0-rocm-7.0.2
  variables:
    CMAKE: /usr/local/cmake-4.0.5/bin/cmake
    GMX_TEST_LABELS: "QuickGpuTest|SlowGpuTest"
    GMX_FORCE_UPDATE_DEFAULT_CPU: 1
    GPU_VENDOR: "NVIDIA"
    GPU_COUNT: 1
  tags:
    - $GITLAB_RUNNER_TAG_1X_NVIDIA_GPU
  needs:
    - job: gromacs:clang-20-cuda-12.8.1:build

gromacs:clang-20-cuda-12.8.1:regressiontest:
  extends:
    - .gromacs:base:regressiontest
  rules:
    - !reference [.rules:skip-if-single-nvidia-gpu-unavailable, rules]
    - !reference [.rules:post-merge-acceptance, rules]
  image: ${CI_REGISTRY}/gromacs/gromacs/ci-ubuntu-24.04-llvm-20-cuda-12.8.1-adaptivecpp-25.10.0-rocm-7.0.2
  variables:
    CMAKE: /usr/local/cmake-4.0.5/bin/cmake
    REGRESSIONTEST_PME_RANK_NUMBER: 0
    REGRESSIONTEST_TOTAL_RANK_NUMBER: 2
    REGRESSIONTEST_OMP_RANK_NUMBER: 1
    GPU_VENDOR: NVIDIA
    GPU_COUNT: 1
  tags:
    - $GITLAB_RUNNER_TAG_1X_NVIDIA_GPU
  needs:
    - job: gromacs:clang-20-cuda-12.8.1:build
    - job: regressiontests:prepare
