# Test goal: Simple Clang build with no GPU
# Test intents (should change rarely and conservatively):
#   OS: Ubuntu oldest supported
#   Compiler: Clang
#   GPU: no
#   Scope: configure, build, unit tests, regression tests
# Test implementation choices (free to change as needed):
#   OS: Ubuntu 22.04
#   Build type: Debug
#   Compiler: Clang 14
#   MPI: thread_MPI
#   SIMD: AVX2_256
#   FFT: FFTW3
#   Parallelism nt/ntomp: 4/2
#   TNG: build without TNG
#   Colvars: build without internal colvars support
#.  PLUMED: build without PLUMED support

gromacs:clang-14:configure:
  extends:
    - .gromacs:base:configure
    - .use-clang:base
  rules:
    - !reference [.rules:merge-requests, rules]
  image: ${CI_REGISTRY}/gromacs/gromacs/ci-ubuntu-22.04-llvm-14-cuda-12.1.0-openmpi-5.0.3
  variables:
    CMAKE: /usr/local/cmake-3.29.8/bin/cmake
    COMPILER_MAJOR_VERSION: 14
    CMAKE_EXTRA_OPTIONS: -DGMX_INSTALL_LEGACY_API=ON -DGMX_USE_TNG=no -DGMX_USE_COLVARS=NONE -DGMX_USE_PLUMED=OFF

gromacs:clang-14:build:
  extends:
    - .gromacs:base:build
    - .before_script:default
    - .use-ccache
  rules:
    - !reference [.rules:merge-requests, rules]
  image: ${CI_REGISTRY}/gromacs/gromacs/ci-ubuntu-22.04-llvm-14-cuda-12.1.0-openmpi-5.0.3
  variables:
    CMAKE: /usr/local/cmake-3.29.8/bin/cmake
  needs:
    - job: gromacs:clang-14:configure

gromacs:clang-14:test:
  extends:
    - .gromacs:base:test
  rules:
    - !reference [.rules:merge-requests, rules]
  image: ${CI_REGISTRY}/gromacs/gromacs/ci-ubuntu-22.04-llvm-14-cuda-12.1.0-openmpi-5.0.3
  variables:
    CMAKE: /usr/local/cmake-3.29.8/bin/cmake
    GMX_FORCE_UPDATE_DEFAULT_CPU: 1
    GMX_FILLERS_IN_LOCAL_STATE: 1
  needs:
    - job: gromacs:clang-14:build

gromacs:clang-14:regressiontest:
  extends:
    - .gromacs:base:regressiontest
  rules:
    - !reference [.rules:merge-requests, rules]
  image: ${CI_REGISTRY}/gromacs/gromacs/ci-ubuntu-22.04-llvm-14-cuda-12.1.0-openmpi-5.0.3
  variables:
    CMAKE: /usr/local/cmake-3.29.8/bin/cmake
    GMX_FILLERS_IN_LOCAL_STATE: 1
  needs:
    - job: gromacs:clang-14:build
    - job: regressiontests:prepare

