# Test goal: Newest oneAPI with SYCL with tests on AMD GPUs
# Test intents (should change rarely and conservatively):
#   OS: Ubuntu newest supported
#   Compiler: oneAPI ICPX newest supported
#   FFT: MKL
#   GPU: SYCL DPC++ (newest supported AMD backend)
#   Scope: configure, build, unit tests, regression tests
# Test implementation choices (free to change as needed):
#   OS: Ubuntu 22.04
#   Build type: RelWithAssert
#   Compiler: ICPX 2024.2
#   GPU: Codeplay plugin for ROCm 6.1.3
#   MPI: thread_MPI
#   SIMD: AVX2_256
#   Parallelism nt/ntomp: 2/1 and 2/2

gromacs:oneapi-2024.2-amd-nightly:configure:
  extends:
   - .gromacs:base:configure
   - .use-oneapi-intel-llvm:base
   - .use-sycl
  rules:
   - !reference [.rules:nightly-not-for-release, rules]
  image: ${CI_REGISTRY}/gromacs/gromacs/ci-ubuntu-22.04-oneapi-2024.2-cuda-12.0.1-rocm-6.1.3:latest
  variables:
    CMAKE: /usr/local/cmake-3.28.0/bin/cmake
    CMAKE_BUILD_TYPE_OPTIONS: "-DCMAKE_BUILD_TYPE=RelWithAssert"
    CMAKE_EXTRA_OPTIONS: "-DSYCL_CXX_FLAGS_EXTRA=-fsycl-targets=amd_gpu_gfx1034 -DGMX_GPU_NB_CLUSTER_SIZE=8 -DGMX_GPU_FFT_LIBRARY=vkfft"
    COMPILER_MAJOR_VERSION: 2024

gromacs:oneapi-2024.2-amd-nightly:build:
  extends:
    - .gromacs:base:build
    - .use-ccache
    - .use-oneapi-intel-llvm:base
  rules:
    - !reference [.rules:nightly-not-for-release, rules]
  image: ${CI_REGISTRY}/gromacs/gromacs/ci-ubuntu-22.04-oneapi-2024.2-cuda-12.0.1-rocm-6.1.3:latest
  variables:
    CMAKE: /usr/local/cmake-3.28.0/bin/cmake
  needs:
    - job: gromacs:oneapi-2024.2-amd-nightly:configure

gromacs:oneapi-2024.2-amd-nightly:test:
  extends:
    - .gromacs:base:test
    - .use-oneapi-intel-llvm:base
  rules:
    - !reference [.rules:skip-if-single-amd-gpu-unavailable, rules]
    - !reference [.rules:nightly-not-for-release, rules]
  image: ${CI_REGISTRY}/gromacs/gromacs/ci-ubuntu-22.04-oneapi-2024.2-cuda-12.0.1-rocm-6.1.3:latest
  variables:
    CMAKE: /usr/local/cmake-3.28.0/bin/cmake
    SYCL_DEVICE_FILTER: "ext_oneapi_hip:gpu"
    GMX_TEST_LABELS: "QuickGpuTest|SlowGpuTest"
    GPU_VENDOR: "AMD"
    GPU_COUNT: 1
  needs:
    - job: gromacs:oneapi-2024.2-amd-nightly:build
  tags:
    - $GITLAB_RUNNER_TAG_1X_AMD_GPU

gromacs:oneapi-2024.2-amd-nightly:regressiontest:
  extends:
    - .gromacs:base:regressiontest
    - .use-oneapi-intel-llvm:base
  rules:
    - !reference [.rules:skip-if-single-amd-gpu-unavailable, rules]
    - !reference [.rules:nightly-not-for-release, rules]
  image: ${CI_REGISTRY}/gromacs/gromacs/ci-ubuntu-22.04-oneapi-2024.2-cuda-12.0.1-rocm-6.1.3:latest
  variables:
    CMAKE: /usr/local/cmake-3.28.0/bin/cmake
    SYCL_DEVICE_FILTER: "ext_oneapi_hip:gpu"
    # Default not working, see #2980
    REGRESSIONTEST_TOTAL_RANK_NUMBER: 2
    REGRESSIONTEST_OMP_RANK_NUMBER: 1
    GPU_VENDOR: "AMD"
    GPU_COUNT: 1
  needs:
    - job: gromacs:oneapi-2024.2-amd-nightly:build
    - job: regressiontests:prepare
  tags:
    - $GITLAB_RUNNER_TAG_1X_AMD_GPU
