# Test goal: Newest ICPX build with SYCL
# Test intents (should change rarely and conservatively):
#   OS: Ubuntu oldest supported
#   Compiler: ICPX newest supported
#   FFT: MKL
#   GPU: SYCL
#   Scope: configure, build, unit tests, regression tests
# Test implementation choices (free to change as needed):
#   OS: Ubuntu 18.04
#   Build type: Debug
#   Compiler: ICPX 2021.1
#   MPI: thread_MPI
#   SIMD: AVX2_256
#   Parallelism nt/ntomp: 4/2

gromacs:oneapi-2021.1.1-sycl:configure:
  extends:
   - .gromacs:base:configure
   - .use-oneapi:base
   - .use-sycl
   - .rules:merge-and-post-merge-acceptance
  image: ${CI_REGISTRY}/gromacs/gromacs/ci-ubuntu-18.04-gcc-7-oneapi-2021.1.1:release-2021
  variables:
    CMAKE: /usr/local/cmake-3.17.2/bin/cmake
    COMPILER_MAJOR_VERSION: 2021

gromacs:oneapi-2021.1.1-sycl:build:
  extends:
    - .variables:default
    - .gromacs:base:build
    - .use-ccache
    - .use-oneapi:base
    - .rules:merge-and-post-merge-acceptance
  image: ${CI_REGISTRY}/gromacs/gromacs/ci-ubuntu-18.04-gcc-7-oneapi-2021.1.1:release-2021
  variables:
    CMAKE: /usr/local/cmake-3.17.2/bin/cmake
  needs:
    - job: gromacs:oneapi-2021.1.1-sycl:configure

gromacs:oneapi-2021.1.1-sycl:test:
  extends:
    - .gromacs:base:test
    - .use-oneapi:base
    - .rules:post-merge-acceptance
  image: ${CI_REGISTRY}/gromacs/gromacs/ci-ubuntu-18.04-gcc-7-oneapi-2021.1.1:release-2021
  variables:
    CMAKE: /usr/local/cmake-3.17.2/bin/cmake
  needs:
    - job: gromacs:oneapi-2021.1.1-sycl:build

gromacs:oneapi-2021.1.1-sycl:regressiontest:
  extends:
    - .gromacs:base:regressiontest
    - .use-oneapi:base
    - .rules:post-merge-acceptance
  image: ${CI_REGISTRY}/gromacs/gromacs/ci-ubuntu-18.04-gcc-7-oneapi-2021.1.1:release-2021
  variables:
    CMAKE: /usr/local/cmake-3.17.2/bin/cmake
  needs:
    - job: gromacs:oneapi-2021.1.1-sycl:build
    - job: regressiontests:prepare

