# Test goal: Clang-CUDA build
# Test intents (should change rarely and conservatively):
#   OS: Ubuntu newest supported
#   GPU: Clang CUDA
#   HW: NVIDIA GPU
#   Scope: configure, build, unit tests, regression tests
# Test implementation choices (free to change as needed):
#   OS: Ubuntu 20.04
#   Build type: RelWithDebInfo
#   Compiler: Clang 12
#   MPI: thread_MPI
#   GPU: Clang CUDA 11.4.3, CUDA 11.4.3
#   SIMD: AVX2_256, no kernels
#   FFT: FFTW3
#   Parallelism nt/ntomp: 4/2 (unit tests)
#   Parallelism nt/ntomp: 2/1 (regression tests)

gromacs:clang-12-cuda-11.4.3:configure:
  extends:
    - .gromacs:base:configure
    - .use-clang:base
    - .use-cuda
    - .rules:post-merge-acceptance
  image: ${CI_REGISTRY}/gromacs/gromacs/ci-ubuntu-20.04-llvm-12-cuda-11.4.3-hipsycl-c1246fd-rocm-5.0
  variables:
    CMAKE: /usr/local/cmake-3.17.2/bin/cmake
    CMAKE_SIMD_OPTIONS: "-DGMX_USE_SIMD_KERNELS=off"
    CMAKE_EXTRA_OPTIONS: "-DGMX_CLANG_CUDA=ON"
    CMAKE_BUILD_TYPE_OPTIONS: "-DCMAKE_BUILD_TYPE=RelWithDebInfo"
    COMPILER_MAJOR_VERSION: 12

gromacs:clang-12-cuda-11.4.3:build:
  extends:
    - .variables:default
    - .gromacs:base:build
    - .use-clang:base
    - .use-ccache
    - .rules:post-merge-acceptance
  image: ${CI_REGISTRY}/gromacs/gromacs/ci-ubuntu-20.04-llvm-12-cuda-11.4.3-hipsycl-c1246fd-rocm-5.0
  variables:
    CMAKE: /usr/local/cmake-3.17.2/bin/cmake
  needs:
    - job: gromacs:clang-12-cuda-11.4.3:configure

gromacs:clang-12-cuda-11.4.3:test:
  extends:
    - .gromacs:base:test
    - .rules:post-merge-acceptance
  image: ${CI_REGISTRY}/gromacs/gromacs/ci-ubuntu-20.04-llvm-12-cuda-11.4.3-hipsycl-c1246fd-rocm-5.0
  variables:
    CMAKE: /usr/local/cmake-3.17.2/bin/cmake
    KUBERNETES_EXTENDED_RESOURCE_NAME: "nvidia.com/gpu"
    KUBERNETES_EXTENDED_RESOURCE_LIMIT: 1
  tags:
    - k8s-scilifelab
  needs:
    - job: gromacs:clang-12-cuda-11.4.3:build

gromacs:clang-12-cuda-11.4.3:regressiontest:
  extends:
    - .gromacs:base:regressiontest
    - .rules:post-merge-acceptance
  image: ${CI_REGISTRY}/gromacs/gromacs/ci-ubuntu-20.04-llvm-12-cuda-11.4.3-hipsycl-c1246fd-rocm-5.0
  variables:
    CMAKE: /usr/local/cmake-3.17.2/bin/cmake
    KUBERNETES_EXTENDED_RESOURCE_NAME: "nvidia.com/gpu"
    KUBERNETES_EXTENDED_RESOURCE_LIMIT: 1
    REGRESSIONTEST_PME_RANK_NUMBER: 0
    REGRESSIONTEST_TOTAL_RANK_NUMBER: 2
    REGRESSIONTEST_OMP_RANK_NUMBER: 1
  tags:
    - k8s-scilifelab
  needs:
    - job: gromacs:clang-12-cuda-11.4.3:build
    - job: regressiontests:prepare

gromacs:clang-12-cuda-11.4.3:test-gpucommupd-cuda-sanitizer:
  extends:
    - .gromacs:base:test
    - .rules:post-merge-acceptance
  image:  ${CI_REGISTRY}/gromacs/gromacs/ci-ubuntu-20.04-llvm-12-cuda-11.4.3-hipsycl-c1246fd-rocm-5.0
  variables:
    CMAKE: /usr/local/cmake-3.17.2/bin/cmake
    KUBERNETES_EXTENDED_RESOURCE_NAME: "nvidia.com/gpu"
    KUBERNETES_EXTENDED_RESOURCE_LIMIT: 1
    GMX_FORCE_UPDATE_DEFAULT_GPU: 1
  script:
    - bash -x admin/ci-scripts/gromacs-base-cuda-sanitizer-test.sh
  tags:
    - k8s-scilifelab
  needs:
    - job: gromacs:clang-12-cuda-11.4.3:configure
    - job: gromacs:clang-12-cuda-11.4.3:build
