# Test goal: Newest ICPX build with SYCL with tests on Intel GPUs
# Test intents (should change rarely and conservatively):
#   OS: Ubuntu newest supported
#   Compiler: ICPX newest supported
#   FFT: MKL
#   GPU: SYCL DPC++ (OpenCL backend)
#   Scope: configure, build, unit tests, regression tests
# Test implementation choices (free to change as needed):
#   OS: Ubuntu 20.04
#   Build type: RelWithAssert
#   Compiler: ICPX 2022.2
#   MPI: thread_MPI
#   SIMD: AVX2_256
#   Parallelism nt/ntomp: 2/1 and 2/2

# We'd ideally want to also run with LevelZero, but it fails (loudly) with a specific configuration
# we use in CI (Xe Max GPU, 5.18 kernel, 22.10.22597 compute-runtime). See #4219.

gromacs:oneapi-2022.2.0-sycl-nightly:configure:
  extends:
   - .gromacs:base:configure
   - .use-oneapi:base
   - .use-sycl
   - .rules:nightly-not-for-release
  image: ${CI_REGISTRY}/gromacs/gromacs/ci-ubuntu-20.04-oneapi-2022.2.0-intel-compute-runtime:latest
  variables:
    CMAKE: /usr/local/cmake-3.18.4/bin/cmake
    CMAKE_BUILD_TYPE_OPTIONS: "-DCMAKE_BUILD_TYPE=RelWithAssert"
    COMPILER_MAJOR_VERSION: 2021

gromacs:oneapi-2022.2.0-sycl-nightly:build:
  extends:
    - .variables:default
    - .gromacs:base:build
    - .use-ccache
    - .use-oneapi:base
    - .rules:nightly-not-for-release
  image: ${CI_REGISTRY}/gromacs/gromacs/ci-ubuntu-20.04-oneapi-2022.2.0-intel-compute-runtime:latest
  variables:
    CMAKE: /usr/local/cmake-3.18.4/bin/cmake
  needs:
    - job: gromacs:oneapi-2022.2.0-sycl-nightly:configure

gromacs:oneapi-2022.2.0-sycl-nightly:test-opencl:
  extends:
    - .gromacs:base:test
    - .use-oneapi:base
    - .rules:nightly-not-for-release
  tags:
    - intel-gpu-dg1
  image: ${CI_REGISTRY}/gromacs/gromacs/ci-ubuntu-20.04-oneapi-2022.2.0-intel-compute-runtime:latest
  variables:
    CMAKE: /usr/local/cmake-3.18.4/bin/cmake
    SYCL_DEVICE_FILTER: "opencl:gpu"
    # The following two variables are not used by k8s, since this job runs on a separate host
    # But it's easier to set them up and use the existing scripts for job preparation that rely on them
    KUBERNETES_EXTENDED_RESOURCE_NAME: "intel.com/gpu"
    KUBERNETES_EXTENDED_RESOURCE_LIMIT: 2
    GMX_TEST_LABELS: "QuickGpuTest|SlowGpuTest"
  needs:
    - job: gromacs:oneapi-2022.2.0-sycl-nightly:build

gromacs:oneapi-2022.2.0-sycl-nightly:test-opencl-upd:
  extends:
    - .gromacs:base:test
    - .use-oneapi:base
    - .rules:nightly-not-for-release
  tags:
    - intel-gpu-dg1
  image: ${CI_REGISTRY}/gromacs/gromacs/ci-ubuntu-20.04-oneapi-2022.2.0-intel-compute-runtime:latest
  variables:
    CMAKE: /usr/local/cmake-3.18.4/bin/cmake
    SYCL_DEVICE_FILTER: "opencl:gpu"
    GMX_FORCE_UPDATE_DEFAULT_GPU: 1
    # The following two variables are not used by k8s, since this job runs on a separate host
    # But it's easier to set them up and use the existing scripts for job preparation that rely on them
    KUBERNETES_EXTENDED_RESOURCE_NAME: "intel.com/gpu"
    KUBERNETES_EXTENDED_RESOURCE_LIMIT: 2
    GMX_TEST_LABELS: "QuickGpuTest|SlowGpuTest"
  needs:
    - job: gromacs:oneapi-2022.2.0-sycl-nightly:build

gromacs:oneapi-2022.2.0-sycl-nightly:regressiontest-opencl:
  extends:
    - .gromacs:base:regressiontest
    - .use-oneapi:base
    - .rules:nightly-not-for-release
  tags:
    - intel-gpu-dg1
  image: ${CI_REGISTRY}/gromacs/gromacs/ci-ubuntu-20.04-oneapi-2022.2.0-intel-compute-runtime:latest
  variables:
    CMAKE: /usr/local/cmake-3.18.4/bin/cmake
    SYCL_DEVICE_FILTER: "opencl:gpu"
    # Default not working, see #2980
    REGRESSIONTEST_TOTAL_RANK_NUMBER: 2
    REGRESSIONTEST_OMP_RANK_NUMBER: 1
    # The following two variables are not used by k8s, since this job runs on a separate host
    # But it's easier to set them up and use the existing scripts for job preparation that rely on them
    KUBERNETES_EXTENDED_RESOURCE_NAME: "intel.com/gpu"
    KUBERNETES_EXTENDED_RESOURCE_LIMIT: 2
  needs:
    - job: gromacs:oneapi-2022.2.0-sycl-nightly:build
    - job: regressiontests:prepare

gromacs:oneapi-2022.2.0-sycl-nightly:regressiontest-opencl-singlerank-upd:
  extends:
    - .gromacs:base:regressiontest
    - .use-oneapi:base
    - .rules:nightly-not-for-release
  tags:
    - intel-gpu-dg1
  image: ${CI_REGISTRY}/gromacs/gromacs/ci-ubuntu-20.04-oneapi-2022.2.0-intel-compute-runtime:latest
  variables:
    CMAKE: /usr/local/cmake-3.18.4/bin/cmake
    SYCL_DEVICE_FILTER: "opencl:gpu"
    # Default not working, see #2980
    REGRESSIONTEST_TOTAL_RANK_NUMBER: 1
    REGRESSIONTEST_OMP_RANK_NUMBER: 1
    GMX_FORCE_UPDATE_DEFAULT_GPU: 1
    # The following two variables are not used by k8s, since this job runs on a separate host
    # But it's easier to set them up and use the existing scripts for job preparation that rely on them
    KUBERNETES_EXTENDED_RESOURCE_NAME: "intel.com/gpu"
    KUBERNETES_EXTENDED_RESOURCE_LIMIT: 2
  needs:
    - job: gromacs:oneapi-2022.2.0-sycl-nightly:build
    - job: regressiontests:prepare


gromacs:oneapi-2022.2.0-sycl-nightly:regressiontest-opencl-upd:
  extends:
    - .gromacs:base:regressiontest
    - .use-oneapi:base
    - .rules:nightly-not-for-release
  tags:
    - intel-gpu-dg1
  image: ${CI_REGISTRY}/gromacs/gromacs/ci-ubuntu-20.04-oneapi-2022.2.0-intel-compute-runtime:latest
  variables:
    CMAKE: /usr/local/cmake-3.18.4/bin/cmake
    SYCL_DEVICE_FILTER: "opencl:gpu"
    # Default not working, see #2980
    REGRESSIONTEST_TOTAL_RANK_NUMBER: 2
    REGRESSIONTEST_OMP_RANK_NUMBER: 1
    GMX_FORCE_UPDATE_DEFAULT_GPU: 1
    # The following two variables are not used by k8s, since this job runs on a separate host
    # But it's easier to set them up and use the existing scripts for job preparation that rely on them
    KUBERNETES_EXTENDED_RESOURCE_NAME: "intel.com/gpu"
    KUBERNETES_EXTENDED_RESOURCE_LIMIT: 2
  needs:
    - job: gromacs:oneapi-2022.2.0-sycl-nightly:build
    - job: regressiontests:prepare

gromacs:oneapi-2022.2.0-sycl-nightly:regressiontest-opencl-singlerank:
  extends:
    - .gromacs:base:regressiontest
    - .use-oneapi:base
    - .rules:nightly-not-for-release
  tags:
    - intel-gpu-dg1
  image: ${CI_REGISTRY}/gromacs/gromacs/ci-ubuntu-20.04-oneapi-2022.2.0-intel-compute-runtime:latest
  variables:
    CMAKE: /usr/local/cmake-3.18.4/bin/cmake
    SYCL_DEVICE_FILTER: "opencl:gpu"
    # Default not working, see #2980
    REGRESSIONTEST_TOTAL_RANK_NUMBER: 1
    REGRESSIONTEST_OMP_RANK_NUMBER: 1
    # The following two variables are not used by k8s, since this job runs on a separate host
    # But it's easier to set them up and use the existing scripts for job preparation that rely on them
    KUBERNETES_EXTENDED_RESOURCE_NAME: "intel.com/gpu"
    KUBERNETES_EXTENDED_RESOURCE_LIMIT: 2
  needs:
    - job: gromacs:oneapi-2022.2.0-sycl-nightly:build
    - job: regressiontests:prepare
