# Test goal: CUDA GPU communications with OpenMPI
# Test intents (should change rarely and conservatively):
#   OS: Ubuntu oldest supported on NGC with the chosen CUDA
#   GPU: NVHPC SDK newest supported with its newest supported CUDA and gcc
#   HW: dual NVIDIA GPU
#   MPI: OpenMPI
#   Features: GPU direct communications (manual) + update (regression tests with dual GPU)
#   Features: Libtorch build + NNPot module + Colvars torchANN (with and without GPU SDK)
#   Scope: configure, build, regression tests
# Test implementation choices (free to change as needed):
#   OS: Ubuntu 24.04
#   Build type: RelWithDebInfo
#   Compiler: GCC 14.2
#   GPU: NVHPC SDK 25.9, CUDA 13.0.2
#   SIMD: SSE 4.1
#   FFT: FFTW3
#   Libtorch: 2.9.0
#   Parallelism np/ntomp: 4/1 (regression tests with dual GPU)

gromacs:gcc-14-cuda-13.0.2:configureMPI:
  extends:
    - .gromacs:base:configure
    - .use-gcc:base
    - .use-cuda
    - .use-mpi
  rules:
    - !reference [.rules:merge-and-post-merge-acceptance, rules]
  image: ${CI_REGISTRY}/gromacs/gromacs/ci-ubuntu-24.04-gcc-14-cuda-13.0.2-libtorch-2.9
  variables:
    CMAKE: /usr/local/cmake-3.29.8/bin/cmake
    CMAKE_SIMD_OPTIONS: "-DGMX_SIMD=SSE4.1"
    # set CUDA_NVRTC_SHORTHASH to an arbitrary value avoid CMake warning due to PyTorch issue #129777
    CMAKE_EXTRA_OPTIONS: "-DGMX_USE_CUFFTMP=ON -DcuFFTMp_ROOT=/opt/nvidia/hpc_sdk/Linux_x86_64/2025/math_libs -DTorch_DIR=/usr/local/libtorch/libtorch/share/cmake/Torch -DGMX_NNPOT=TORCH -Wno-dev -DCUDA_NVRTC_SHORTHASH=PYTORCHISSUE129777"
    COMPILER_MAJOR_VERSION: 14

gromacs:gcc-14-cuda-13.0.2:buildMPI:
  extends:
    - .gromacs:base:build
    - .before_script:default
    - .use-ccache
  rules:
    - !reference [.rules:merge-and-post-merge-acceptance, rules]
  image: ${CI_REGISTRY}/gromacs/gromacs/ci-ubuntu-24.04-gcc-14-cuda-13.0.2-libtorch-2.9
  variables:
    CMAKE: /usr/local/cmake-3.29.8/bin/cmake
  needs:
    - job: gromacs:gcc-14-cuda-13.0.2:configureMPI

gromacs:gcc-14-cuda-13.0.2:testMPI:
  extends:
    - .gromacs:base:test
  rules:
    - !reference [.rules:skip-if-single-nvidia-gpu-unavailable, rules]
    - !reference [.rules:merge-and-post-merge-acceptance, rules]
  image: ${CI_REGISTRY}/gromacs/gromacs/ci-ubuntu-24.04-gcc-14-cuda-13.0.2-libtorch-2.9
  variables:
    CMAKE: /usr/local/cmake-3.29.8/bin/cmake
    GMX_GPU_PME_DECOMPOSITION: 1
    GMX_TEST_LABELS: "QuickGpuTest|SlowGpuTest"
    GPU_VENDOR: "NVIDIA"
    GPU_COUNT: 1
  tags:
    - $GITLAB_RUNNER_TAG_1X_NVIDIA_GPU
  needs:
    - job: gromacs:gcc-14-cuda-13.0.2:buildMPI

gromacs:gcc-14-cuda-13.0.2:regressiontest-gpucommupd-MPI:
  # Test parallelism np/ntomp: 4/1
  # Test parallelism GPU: direct communications, update
  extends:
    - .gromacs:base:regressiontest
  rules:
    - !reference [.rules:skip-if-dual-nvidia-gpus-unavailable, rules]
    - !reference [.rules:post-merge-acceptance, rules]
  image: ${CI_REGISTRY}/gromacs/gromacs/ci-ubuntu-24.04-gcc-14-cuda-13.0.2-libtorch-2.9
  variables:
    CMAKE: /usr/local/cmake-3.29.8/bin/cmake
    REGRESSIONTEST_PME_RANK_NUMBER: 0
    REGRESSIONTEST_TOTAL_RANK_NUMBER: 4
    REGRESSIONTEST_OMP_RANK_NUMBER: 1
    REGRESSIONTEST_PARALLEL: "-np"  
    GPU_VENDOR: "NVIDIA"
    GPU_COUNT: 2
  tags:
    - $GITLAB_RUNNER_TAG_2X_NVIDIA_GPU
  needs:
    - job: gromacs:gcc-14-cuda-13.0.2:buildMPI
    - job: regressiontests:prepare
  artifacts:
    paths:
      - regressiontests
    when: always
    expire_in: 1 week

gromacs:gcc-14:configure-libtorch:
  extends:
    - .gromacs:base:configure
    - .use-gcc:base
    # need CUDA even if not using GPU for NNPot, because libtorch is built with CUDA and needs to find it
    - .use-cuda
  rules:
    - !reference [.rules:nightly-not-for-release, rules]
  image: ${CI_REGISTRY}/gromacs/gromacs/ci-ubuntu-24.04-gcc-14-cuda-13.0.2-libtorch-2.9
  variables:
    CMAKE: /usr/local/cmake-3.28.0/bin/cmake
    CMAKE_SIMD_OPTIONS: "-DGMX_SIMD=AVX_512"
    # set CUDA_NVRTC_SHORTHASH to an arbitrary value avoid CMake warning due to PyTorch issue #129777
    CMAKE_EXTRA_OPTIONS: "-DCMAKE_BUILD_TYPE=Debug -DGMX_GPU=OFF -DTorch_DIR=/usr/local/libtorch/libtorch/share/cmake/Torch -DGMX_NNPOT=TORCH -Wno-dev -DCUDA_NVRTC_SHORTHASH=PYTORCHISSUE129777"
    COMPILER_MAJOR_VERSION: 14

gromacs:gcc-14:build-libtorch:
  extends:
    - .gromacs:base:build
    - .before_script:default
    - .use-ccache
  rules:
    - !reference [.rules:nightly-not-for-release, rules]
  image: ${CI_REGISTRY}/gromacs/gromacs/ci-ubuntu-24.04-gcc-14-cuda-13.0.2-libtorch-2.9
  variables:
    CMAKE: /usr/local/cmake-3.28.0/bin/cmake
  needs:
    - job: gromacs:gcc-14:configure-libtorch
