# Test goal: Clang static analyzer build
# Test intents (should change rarely and conservatively):
#   OS: Ubuntu oldest supported
#   Compiler: Clang
#   Build type: Static Analuzer
#   GPU: no
#   SIMD: no
#   FFT: fftpack
#   MPI: thread_MPI
#   Scope: configure, build
# Test implementation choices (free to change as needed):
#   OS: Ubuntu 20.04
#   Compiler: Clang 11

gromacs:clang-static-analyzer:configure:
  extends:
    - .gromacs:base:configure
    - .use-clang:base
  rules:
    - !reference [.rules:merge-requests, rules]
  image: ${CI_REGISTRY}/gromacs/gromacs/ci-ubuntu-20.04-llvm-11-tsan
  variables:
    CMAKE: /usr/local/cmake-3.18.4/bin/cmake
    CMAKE_COMPILER_SCRIPT: "-DCMAKE_CXX_COMPILER=/usr/local/libexec/c++-analyzer -DCMAKE_C_COMPILER=gcc"
    CMAKE_EXTRA_OPTIONS: "-DGMX_CLANG_ANALYZER=ON -DGMX_OPENMP=OFF -DGMX_USE_RDTSCP=OFF -DGMX_FFT_LIBRARY=fftpack -DGMX_DEVELOPER_BUILD=ON"
    CMAKE_SIMD_OPTIONS: "-DGMX_SIMD=None"

gromacs:clang-static-analyzer:build:
  extends:
    - .gromacs:static-analyzer-build
    - .use-clang:base
    - .use-ccache
  rules:
    - !reference [.rules:merge-requests, rules]
  image: ${CI_REGISTRY}/gromacs/gromacs/ci-ubuntu-20.04-llvm-11-tsan
  variables:
    CMAKE: /usr/local/cmake-3.18.4/bin/cmake
  needs:
    - job: gromacs:clang-static-analyzer:configure

