# Test goal: Clang build with MPI and double precision
# Test intents (should change rarely and conservatively):
#   OS: Ubuntu oldest supported
#   Compiler: Clang newest supported
#   GPU: no
#   MPI: OpenMPI
#   Features: double precision FP, two-wide SIMD
#   Scope: configure, build, unit tests, regression tests
# Test implementation choices (free to change as needed):
#   OS: Ubuntu 20.04
#   Build type: Debug
#   Compiler: Clang 17
#   MPI: OpenMPI 3.1
#   SIMD: SSE4.1
#   FFT: FFTW3
#   Parallelism np/ntomp: 4/2
#   Subcyclecounting: Active

gromacs:clang-17-mpi:configure:
  extends:
   - .gromacs:base:configure
   - .use-clang:base
   - .use-mpi
  rules:
   - !reference [.rules:merge-requests, rules]
  image: ${CI_REGISTRY}/gromacs/gromacs/ci-ubuntu-20.04-llvm-17
  variables:
    CMAKE: /usr/local/cmake-3.18.4/bin/cmake
    COMPILER_MAJOR_VERSION: 17
    CMAKE_PRECISION_OPTIONS: -DGMX_DOUBLE=ON
    CMAKE_EXTRA_OPTIONS: -DGMX_CYCLE_SUBCOUNTERS=ON -DGMX_INSTALL_LEGACY_API=ON
    CMAKE_SIMD_OPTIONS: "-DGMX_SIMD=SSE4.1"

gromacs:clang-17-mpi:build:
  # Test using configuration: gromacs:clang-17-mpi:configure
  # Test scope: build
  extends:
    - .gromacs:base:build
    - .before_script:default
    - .use-ccache
  rules:
    - !reference [.rules:merge-requests, rules]
  image: ${CI_REGISTRY}/gromacs/gromacs/ci-ubuntu-20.04-llvm-17
  variables:
    CMAKE: /usr/local/cmake-3.18.4/bin/cmake
  needs:
    - job: gromacs:clang-17-mpi:configure

gromacs:clang-17-mpi:test:
  extends:
    - .gromacs:base:test
  rules:
    - !reference [.rules:merge-requests, rules]
  image: ${CI_REGISTRY}/gromacs/gromacs/ci-ubuntu-20.04-llvm-17
  variables:
    CMAKE: /usr/local/cmake-3.18.4/bin/cmake
  needs:
    - job: gromacs:clang-17-mpi:build

gromacs:clang-17:regressiontest:
  extends:
    - .gromacs:base:regressiontest
  rules:
    - !reference [.rules:merge-requests, rules]
  image: ${CI_REGISTRY}/gromacs/gromacs/ci-ubuntu-20.04-llvm-17
  variables:
    CMAKE: /usr/local/cmake-3.18.4/bin/cmake
    REGRESSIONTEST_DOUBLE: "-double"
    REGRESSIONTEST_PARALLEL: "-np"
    GMX_FORCE_UPDATE_DEFAULT_CPU: 1
  needs:
    - job: gromacs:clang-17-mpi:build
    - job: regressiontests:prepare

