# Test goal: Newest ICPX build with OpenCL
# Test intents (should change rarely and conservatively):
#   OS: Ubuntu oldest supported
#   Compiler: ICPX newest supported
#   FFT: MKL
#   GPU: OpenCL
#   Scope: configure, build, unit tests, regression tests
# Test implementation choices (free to change as needed):
#   OS: Ubuntu 22.04
#   Build type: Debug
#   Compiler: ICPX 2024.0
#   MPI: thread_MPI
#   SIMD: AVX2_256
#   Parallelism nt/ntomp: 4/2

gromacs:oneapi-2024.0-opencl:configure:
  extends:
   - .gromacs:base:configure
   - .use-oneapi:base
   - .use-opencl
  rules:
   - !reference [.rules:merge-requests, rules]
  image: ${CI_REGISTRY}/gromacs/gromacs/ci-ubuntu-22.04-oneapi-2024.0-intel-compute-runtime
  variables:
    CMAKE: /usr/local/cmake-3.18.4/bin/cmake
    COMPILER_MAJOR_VERSION: 2024

gromacs:oneapi-2024.0-opencl:build:
  extends:
    - .gromacs:base:build
    - .use-ccache
    - .use-oneapi:base
  rules:
    - !reference [.rules:merge-requests, rules]
  image: ${CI_REGISTRY}/gromacs/gromacs/ci-ubuntu-22.04-oneapi-2024.0-intel-compute-runtime
  variables:
    CMAKE: /usr/local/cmake-3.18.4/bin/cmake
  needs:
    - job: gromacs:oneapi-2024.0-opencl:configure

gromacs:oneapi-2024.0-opencl:test:
  extends:
    - .gromacs:base:test
    - .use-oneapi:base
  rules:
    - !reference [.rules:merge-requests, rules]
  image: ${CI_REGISTRY}/gromacs/gromacs/ci-ubuntu-22.04-oneapi-2024.0-intel-compute-runtime
  variables:
    CMAKE: /usr/local/cmake-3.18.4/bin/cmake
    GMX_FORCE_UPDATE_DEFAULT_CPU: 1
  needs:
    - job: gromacs:oneapi-2024.0-opencl:build

gromacs:oneapi-2024.0-opencl:regressiontest:
  extends:
    - .gromacs:base:regressiontest
    - .use-oneapi:base
  rules:
    - !reference [.rules:merge-requests, rules]
  image: ${CI_REGISTRY}/gromacs/gromacs/ci-ubuntu-22.04-oneapi-2024.0-intel-compute-runtime
  variables:
    CMAKE: /usr/local/cmake-3.18.4/bin/cmake
  needs:
    - job: gromacs:oneapi-2024.0-opencl:build
    - job: regressiontests:prepare

