# Test goal: Release build with Clang, MPI, and double-precision
# Test intents (should change rarely and conservatively):
#   OS: Ubuntu oldest supported
#   Compiler: Clang newest supported
#   MPI: OpenMPI
#   GPU: no
#   Features: double precision FP
#   Scope: configure, build, unit tests, regression tests
# Test implementation choices (free to change as needed):
#   OS: Ubuntu 20.04
#   Build type: RelWithAssert
#   Compiler: Clang 17
#   MPI: OpenMPI 3.1
#   SIMD: AVX_512
#   FFT: FFTW3
#   Parallelism np/ntomp: 4/2

gromacs:clang-17:release:configure:
  extends:
    - .gromacs:base:release:configure
    - .use-clang:base
    - .use-mpi
  rules:
    - !reference [.rules:nightly-only-for-release, rules]
  image: ${CI_REGISTRY}/gromacs/gromacs/ci-ubuntu-20.04-llvm-17
  variables:
    CMAKE: /usr/local/cmake-3.18.4/bin/cmake
    COMPILER_MAJOR_VERSION: 17
    RELEASE_BUILD_DIR: release-builds-clang
    CMAKE_PRECISION_OPTIONS: "-DGMX_DOUBLE=ON"
    CMAKE_BUILD_TYPE_OPTIONS: "-DCMAKE_BUILD_TYPE=RelWithAssert"
    CMAKE_SIMD_OPTIONS: "-DGMX_SIMD=AVX_512"
  dependencies:
    - archive:package
    - regressiontests:package
    - prepare-release-version

gromacs:clang-17:release:build:
  extends:
    - .gromacs:base:build
    - .before_script:default
    - .use-ccache
  stage: release-build
  rules:
    - !reference [.rules:nightly-only-for-release, rules]
  variables:
    CMAKE: /usr/local/cmake-3.18.4/bin/cmake
    BUILD_DIR: release-builds-clang
  image: ${CI_REGISTRY}/gromacs/gromacs/ci-ubuntu-20.04-llvm-17
  needs:
    - job: gromacs:clang-17:release:configure

gromacs:clang-17:release:test:
  extends:
    - .gromacs:base:test
  stage: release-tests
  rules:
    - !reference [.rules:nightly-only-for-release, rules]
  image: ${CI_REGISTRY}/gromacs/gromacs/ci-ubuntu-20.04-llvm-17
  variables:
    CMAKE: /usr/local/cmake-3.18.4/bin/cmake
    BUILD_DIR: release-builds-clang
  needs:
    - job: gromacs:clang-17:release:configure
    - job: gromacs:clang-17:release:build

gromacs:clang-17:release:regressiontest:
  extends:
    - .gromacs:base:regressiontest
  stage: release-tests
  rules:
    - !reference [.rules:nightly-only-for-release, rules]
  image: ${CI_REGISTRY}/gromacs/gromacs/ci-ubuntu-20.04-llvm-17
  variables:
    CMAKE: /usr/local/cmake-3.18.4/bin/cmake
    BUILD_DIR: release-builds-clang
    REGRESSIONTEST_DOUBLE: "-double"
    REGRESSIONTEST_PARALLEL: "-np"
  needs:
    - job: gromacs:clang-17:release:build
    - job: regressiontests:package

