# Recipe for build and integration testing on Travis-CI

# Try beta version of new travis-yml checker
version: "= 0"
# For extra debugging of failed jobs, see
# https://docs.travis-ci.com/user/common-build-problems/#Troubleshooting-Locally-in-a-Docker-Image

os: linux
dist: xenial
language: cpp

# If we set 'ccache: true', Travis installs replacement ccache wrappers of system compilers, which we don't want,
# so we'll do our own ccache management.
# Note the heuristics for whether cache is shared or distinct:
# https://docs.travis-ci.com/user/caching/#Caches-and-build-matrices
cache:
  pip: true
  directories:
    # Note: if a cache store forks due to a stage with parallel jobs that Travis identifies as part of the same flow,
    # we must make sure that the parallel jobs do not write to any of the same caches. Also note that all stages use the
    # same cache, so early stage jobs may see caches from later stages from previous builds in the same branch.
    - $HOME/.ccache_gromacs
    - $HOME/.ccache_py
# Allows us to build and install GROMACS in one CI stage, then use the installation in a subsequent stage
#    - $HOME/install

compiler: gcc

env:
# Python 2.7 and 3.6 are the only generations provided by pyenv on Travis-CI out-of-the-box
  - PY=2.7
  - PY=3.6

addons:
  apt:
    sources:
    - sourceline: 'ppa:ubuntu-toolchain-r/test'
    packages:
    - cmake
    - cmake-data
    - doxygen
    - libblas-dev
    - libcr-dev
    - libfftw3-dev
    - liblapack-dev
    - libmpich-dev
    - libxml2-dev
    - mpich

# Set up for all jobs
before_install:
  - pyenv versions
  # get exactly one Python version: the last listed patch version for the selected minor version
  - pyenv whence python${PY} && export PY_VER=`pyenv whence python${PY} | tail -1`
  - pyenv shell $PY_VER && pyenv shell
#  - python-config --includes
  - pyenv prefix ${PY_VER} && export PYTHON_PREFIX=`pyenv prefix ${PY_VER}`
  - pyenv which python && export PYTHON=`pyenv which python`
  - source ./ci_scripts/set_compilers

install:
  - export CCACHE_DIR=$HOME/.ccache_gromacs
  - ccache -s
  - ./ci_scripts/install_gromacs_2019.sh
# Need to update infrastructure for new CMake version requirements to build against devel.
#  - if [ "${TRAVIS_BRANCH}" != "master" ] ; then ./ci_scripts/install_gromacs_devel.sh ; fi

before_script:
  - export CCACHE_DIR=$HOME/.ccache_py
  - ccache -s
  - pip install --upgrade pip setuptools
  - pip install --upgrade packaging
  - pip install --no-cache-dir --upgrade --no-binary ":all:" --force-reinstall networkx mpi4py MarkupSafe
  - pip install pytest numpy networkx sphinx sphinx_rtd_theme

script:
  - source $HOME/install/gromacs_2019/bin/GMXRC && ./ci_scripts/pygmx_0_0_7.sh
  - ./ci_scripts/sample_restraint.sh
# Need to update infrastructure for new CMake version requirements to build against devel.
#  - |
#    if [ "${TRAVIS_BRANCH}" != master ] ; then
#      source $HOME/install/gromacs_devel/bin/GMXRC
#      ./ci_scripts/pygmx_devel.sh
#      ./ci_scripts/sample_restraint.sh
#    fi
